<?php
class addSampleData
{
    private $connec; //connection object to interact with db
    public static function instance() //singleton function
    {
        static $instance = null;
        if ($instance === null)
            $instance = new addSampleData();
        return $instance;
    }
    private function __construct() //connecting to the db using environment variables in .env file
    {
        $this->connec = new mysqli($_ENV['DBHOST'], $_ENV['DBUSERNAME'], $_ENV['DBPASSWORD']);
        if ($this->connec->connect_error)
            die("Connection failure: " . $this->connec->connect_error);
        else {
            $this->connec->select_db($_ENV['MAINDBNAME']);
        }
    }
    public function __destruct() //destructor closes connection
    {
        $this->connec->close();
    }

    public function loadSampleData()
    {
        addSampleData::clearTables();
        // addSampleData::populateUsers();
        addSampleData::populateVenues();
        addSampleData::populateTeams();
        addSampleData::populateAthletes();
        addSampleData::populateEvents();
        addSampleData::populateDuration();
        addSampleData::populateResults();
    }

    private function clearTables()
    {
        $qry = "";
        $qry .= "DELETE FROM `results`;";
        $qry .= "DELETE FROM `duration_of_event`;";
        $qry .= "DELETE FROM `100m sprint`;";
        // $qry .= "DELETE FROM `users`;";
        $qry .= "DELETE FROM `athlete`;";
        $qry .= "DELETE FROM `team`;";
        $qry .= "DELETE FROM `venues`;";
        $qry .= "ALTER TABLE results AUTO_INCREMENT = 0;";
        // $qry .= "ALTER TABLE users AUTO_INCREMENT = 0;";
        $qry .= "ALTER TABLE team AUTO_INCREMENT = 0;";
        $qry .= "ALTER TABLE athlete AUTO_INCREMENT = 0;";
        $qry .= "ALTER TABLE `100m sprint` AUTO_INCREMENT = 0;";
        $qry .= "ALTER TABLE venues AUTO_INCREMENT = 0;";
        $this->connec->multi_query($qry);
        do {
            if ($result = $this->connec->store_result()) {
                $result->free();
            }
        } while ($this->connec->next_result());
    }

    private function populateVenues()
    {
        $VType = "Track & Field";
        $stmt = $this->connec->prepare("INSERT INTO venues (Venue_Name, Venue_Type, Location) VALUES (?, ?, ?)");
        $stmt->bind_param("sss", $VName, $VType, $VLocation);

        $VName = "Sydney Olympic Stadium";
        $VLocation = "Australia";
        $stmt->execute();
        $VName = "London Olympic Stadium";
        $VLocation = "Great Britian";
        $stmt->execute();
        $VName = "Rio de Janeiro Estadio Olimpico";
        $VLocation = "Brazil";
        $stmt->execute();
        $VName = "Tokyo Olympic Stadium";
        $VLocation = "Japan";
        $stmt->execute();
        return;
    }

    private function populateTeams()
    {
        $TRank = 0;
        $stmt = $this->connec->prepare("INSERT INTO team (Team_Name, Country, Ranking) VALUES (?, ?, ?)");
        $stmt->bind_param("ssi", $TName, $TCountry, $TRank);

        $set = " national team";
        $TName =  "Greek national team";
        $TCountry = "Greece";
        $stmt->execute();
        $TName =  "Jamaican national team";
        $TCountry = "Jamaica";
        $stmt->execute();
        $TName = "Ukrainian national team";
        $TCountry = "Ukraine";
        $stmt->execute();
        $TName = "Bahaman national team";
        $TCountry = "Bahamas";
        $stmt->execute();
        $TName = "USA national team";
        $TCountry = "United States of America";
        $stmt->execute();
        $TName = "British national team";
        $TCountry = "Great Britian";
        $stmt->execute();
        $TName = "Ghanan national team";
        $TCountry = "Ghana";
        $stmt->execute();
        $TName = "Tunisian national team";
        $TCountry = "Tunisia";
        $stmt->execute();
        $TName = "Barbadon national team";
        $TCountry = "Barbados";
        $stmt->execute();
        $TName = "Saint Kitts and Nevis national team";
        $TCountry = "Saint Kitts and Nevis";
        $stmt->execute();
        $TName = "Cote d'Ivoire national team";
        $TCountry = "Cote d'Ivoire";
        $stmt->execute();
        $TName = "Nigerian national team";
        $TCountry = "Nigeria";
        $stmt->execute();
        $TName = "Netherlands national team";
        $TCountry = "Netherlands";
        $stmt->execute();
        $TName = "Canadian national team";
        $TCountry = "Canada";
        $stmt->execute();
        $TName = "South African national team";
        $TCountry = "South Africa";
        $stmt->execute();
        $TName = "French national team";
        $TCountry = "France";
        $stmt->execute();
        $TName = "Swiss national team";
        $TCountry = "Switzerland";
        $stmt->execute();
        $TName = "Italian national team";
        $TCountry = "Italy";
        $stmt->execute();
        $TName = "Chinese national team";
        $TCountry = "China";
        $stmt->execute();
        $TName = "Trinidad and Tobago national team";
        $TCountry = "Trinidad and Tobago";
        $stmt->execute();
    }

    private function populateAthletes()
    {
        $stmt = $this->connec->prepare("INSERT INTO athlete (DOB, Name, Sex, ID_Team) VALUES (?, ?, ?, ?)");
        $stmt->bind_param("sssi", $dob, $name, $sex, $team);
        $dob = "1975-02-01";
        $name = "Katerina Thanou";
        $sex = "F";
        $team = 1;
        $stmt->execute();
        $dob = "1975-09-17";
        $name = "Tanya Lawrence";
        $sex = "F";
        $team = 2;
        $stmt->execute();
        $dob = "1960-05-10";
        $name = "Marlene Ottey";
        $sex = "F";
        $team = 2;
        $stmt->execute();
        $dob = "1972-06-06";
        $name = "Zhanna Block";
        $sex = "F";
        $team = 3;
        $stmt->execute();
        $dob = "1971-09-12";
        $name = "Chandra Sturrup";
        $sex = "F";
        $team = 4;
        $stmt->execute();
        $dob = "1974-10-17";
        $name = "Savatheda Fynes";
        $sex = "F";
        $team = 4;
        $stmt->execute();
        $dob = "1976-01-16";
        $name = "Debbie Ferguson-Mckenzie";
        $sex = "F";
        $team = 4;
        $stmt->execute();
        $dob = "1975-10-12";
        $name = "Marion Jones";
        $sex = "F";
        $team = 5;
        $stmt->execute();

        $dob = "1974-07-23";
        $name = "Maurice Greene";
        $sex = "M";
        $team = 5;
        $stmt->execute();
        $dob = "1973-12-30";
        $name = "Ato Boldon";
        $sex = "M";
        $team = 8;
        $stmt->execute();
        $dob = "1976-03-30";
        $name = "Obadele Thompson";
        $sex = "M";
        $team = 9;
        $stmt->execute();
        $dob = "1978-04-05";
        $name = "Dwain Chambers";
        $sex = "M";
        $team = 6;
        $stmt->execute();
        $dob = "1968-09-09";
        $name = "Jon Drummond";
        $sex = "M";
        $team = 5;
        $stmt->execute();
        $dob = "1973-09-12";
        $name = "Darren Campbell";
        $sex = "M";
        $team = 6;
        $stmt->execute();
        $dob = "1976-04-05";
        $name = "Kim Collins";
        $sex = "M";
        $team = 10;
        $stmt->execute();
        $dob = "1976-09-02";
        $name = "Aziz Zakari";
        $sex = "M";
        $team = 7;
        $stmt->execute();

        $dob = "1986-12-27";
        $name = "Shelly-Ann Fraser-Pryce";
        $sex = "F";
        $team = 2;
        $stmt->execute();
        $dob = "1979-11-24";
        $name = "Carmelita Jeter";
        $sex = "F";
        $team = 5;
        $stmt->execute();
        $dob = "1982-05-15";
        $name = "Veronica Campbell-Brown";
        $sex = "F";
        $team = 2;
        $stmt->execute();
        $dob = "1985-08-30";
        $name = "Tianna Baroletta";
        $sex = "F";
        $team = 5;
        $stmt->execute();
        $dob = "1985-11-18";
        $name = "Allyson Felix";
        $sex = "F";
        $team = 5;
        $stmt->execute();
        $dob = "1986-10-14";
        $name = "Kelly-Ann Baptiste";
        $sex = "F";
        $team = 20;
        $stmt->execute();
        $dob = "1987-08-23";
        $name = "Murielle Ahoure";
        $sex = "F";
        $team = 11;
        $stmt->execute();
        $dob = "1988-10-09";
        $name = "Blessing Okagbare";
        $sex = "F";
        $team = 12;
        $stmt->execute();

        $dob = "1986-09-21";
        $name = "Usain Bolt";
        $sex = "M";
        $team = 2;
        $stmt->execute();
        $dob = "1989-12-26";
        $name = "Yohan Blake";
        $sex = "M";
        $team = 2;
        $stmt->execute();
        $dob = "1982-02-10";
        $name = "Justin Gatlin";
        $sex = "M";
        $team = 5;
        $stmt->execute();
        $dob = "1989-04-13";
        $name = "Ryan Bailey";
        $sex = "M";
        $team = 5;
        $stmt->execute();
        $dob = "1984-06-03";
        $name = "Churandy Martina";
        $sex = "M";
        $team = 13;
        $stmt->execute();
        $dob = "1985-07-07";
        $name = "Richard Thompson";
        $sex = "M";
        $team = 20;
        $stmt->execute();
        $dob = "1982-11-23";
        $name = "Asafa Powell";
        $sex = "M";
        $team = 2;
        $stmt->execute();
        $dob = "1982-09-09";
        $name = "Tyson Gay";
        $sex = "M";
        $team = 5;
        $stmt->execute();

        $dob = "1992-06-28";
        $name = "Elaine Thompson";
        $sex = "F";
        $team = 2;
        $stmt->execute();
        $dob = "1990-09-27";
        $name = "Tori Bowie";
        $sex = "F";
        $team = 5;
        $stmt->execute();
        $dob = "1986-12-27";
        $name = "Marie-Josee Ta Lou";
        $sex = "F";
        $team = 11;
        $stmt->execute();
        $dob = "1988-11-18";
        $name = "Dafne Schippers";
        $sex = "F";
        $team = 13;
        $stmt->execute();
        $dob = "1992-04-10";
        $name = "Michelle-Lee Ahye";
        $sex = "F";
        $team = 20;
        $stmt->execute();
        $dob = "1992-04-22";
        $name = "English Gardner";
        $sex = "F";
        $team = 5;
        $stmt->execute();
        $dob = "1994-10-17";
        $name = "Christania Williams";
        $sex = "F";
        $team = 2;
        $stmt->execute();

        $dob = "1994-11-10";
        $name = "Andre de Grasse";
        $sex = "M";
        $team = 14;
        $stmt->execute();
        $dob = "1993-09-21";
        $name = "Akani Simbine";
        $sex = "M";
        $team = 15;
        $stmt->execute();
        $dob = "1986-11-11";
        $name = "Ben Youssef Meite";
        $sex = "M";
        $team = 11;
        $stmt->execute();
        $dob = "1992-02-27";
        $name = "Jimmy Vicaut";
        $sex = "M";
        $team = 16;
        $stmt->execute();
        $dob = "1995-07-10";
        $name = "Trayvon Bromell";
        $sex = "M";
        $team = 5;
        $stmt->execute();

        $dob = "1994-07-16";
        $name = "Shericka Jackson";
        $sex = "F";
        $team = 2;
        $stmt->execute();
        $dob = "1996-07-15";
        $name = "Ajla del Ponte";
        $sex = "F";
        $team = 17;
        $stmt->execute();
        $dob = "1992-07-17";
        $name = "Mujinga Kambundji";
        $sex = "F";
        $team = 17;
        $stmt->execute();
        $dob = "1997-03-25";
        $name = "Teahna Daniels";
        $sex = "F";
        $team = 5;
        $stmt->execute();
        $dob = "1996-08-29";
        $name = "Daryll Neita";
        $sex = "F";
        $team = 6;
        $stmt->execute();

        $dob = "1994-09-26";
        $name = "Lamont Marcell Jacobs";
        $sex = "M";
        $team = 18;
        $stmt->execute();
        $dob = "1995-05-07";
        $name = "Fred Kerley";
        $sex = "M";
        $team = 5;
        $stmt->execute();
        $dob = "1993-10-15";
        $name = "Ronnie Baker";
        $sex = "M";
        $team = 5;
        $stmt->execute();
        $dob = "1989-08-29";
        $name = "Bingtian Su";
        $sex = "M";
        $team = 19;
        $stmt->execute();
        $dob = "2000-03-08";
        $name = "Enoch Adegoke";
        $sex = "M";
        $team = 12;
        $stmt->execute();
        $dob = "1995-07-13";
        $name = "Zharnel Hughes";
        $sex = "M";
        $team = 6;
        $stmt->execute();
    }

    private function populateEvents()
    {
        $stmt = $this->connec->prepare("INSERT INTO `100m sprint` (Event_Name, Event_Type, Venue) VALUES (?, ?, ?)");
        $stmt->bind_param("ssi", $EName, $EType, $EVenue);

        $EName = "27th Olympic Games";
        $EType = "Women Final";
        $EVenue = 1;
        $stmt->execute();
        $EName = "27th Olympic Games";
        $EType = "Men Final";
        $EVenue = 1;
        $stmt->execute();
        $EName = "The XXX Olympic Games";
        $EType = "Women Final";
        $EVenue = 2;
        $stmt->execute();
        $EName = "The XXX Olympic Games";
        $EType = "Men Final";
        $EVenue = 2;
        $stmt->execute();
        $EName = "The XXXI Olympic Games";
        $EType = "Women Final";
        $EVenue = 3;
        $stmt->execute();
        $EName = "The XXXI Olympic Games";
        $EType = "Men Final";
        $EVenue = 3;
        $stmt->execute();
        $EName = "The XXXII Olympic Games";
        $EType = "Women Final";
        $EVenue = 4;
        $stmt->execute();
        $EName = "The XXXII Olympic Games";
        $EType = "Men Final";
        $EVenue = 4;
        $stmt->execute();
    }

    private function populateDuration()
    {
        $stmt = $this->connec->prepare("INSERT INTO duration_of_event VALUES (?, ?, ?)");
        $stmt->bind_param("iss", $event, $start, $end);
        $event = 1;
        $start = "2000-09-22";
        $end = "2000-10-01";
        $stmt->execute();
        $event = 2;
        $start = "2000-09-22";
        $end = "2000-10-01";
        $stmt->execute();
        $event = 3;
        $start = "2012-06-27";
        $end = "2012-08-12";
        $stmt->execute();
        $event = 4;
        $start = "2012-06-27";
        $end = "2012-08-12";
        $stmt->execute();
        $event = 5;
        $start = "2016-08-05";
        $end = "2016-08-21";
        $stmt->execute();
        $event = 6;
        $start = "2016-08-05";
        $end = "2016-08-21";
        $stmt->execute();
        $event = 7;
        $start = "2021-07-30";
        $end = "2021-08-08";
        $stmt->execute();
        $event = 8;
        $start = "2021-07-30";
        $end = "2021-08-08";
        $stmt->execute();
    }

    private function populateResults()
    {
        $stmt = $this->connec->prepare("INSERT INTO results (Position, Time, Match_event, ID_Athlete) VALUES (?, ?, ?, ?)");
        $stmt->bind_param("isii", $pos, $time, $event, $athlete);
        $pos = 1;
        $time = "00:00:11.12";
        $event = 1;
        $athlete = 1;
        $stmt->execute();
        $pos = 2;
        $time = "00:00:11.18";
        $athlete = 2;
        $stmt->execute();
        $pos = 3;
        $time = "00:00:11.19";
        $athlete = 3;
        $stmt->execute();
        $pos = 4;
        $time = "00:00:11.20";
        $athlete = 4;
        $stmt->execute();
        $pos = 5;
        $time = "00:00:11.21";
        $athlete = 5;
        $stmt->execute();
        $pos = 6;
        $time = "00:00:11.22";
        $athlete = 6;
        $stmt->execute();
        $pos = 7;
        $time = "00:00:11.29";
        $athlete = 7;
        $stmt->execute();
        $pos = 8;
        $time = "00:00:11.30";
        $athlete = 8;
        $stmt->execute();

        $pos = 1;
        $time = "00:00:09.87";
        $event = 2;
        $athlete = 9;
        $stmt->execute();
        $pos = 2;
        $time = "00:00:09.99";
        $athlete = 10;
        $stmt->execute();
        $pos = 3;
        $time = "00:00:10.04";
        $athlete = 11;
        $stmt->execute();
        $pos = 4;
        $time = "00:00:10.08";
        $athlete = 12;
        $stmt->execute();
        $pos = 5;
        $time = "00:00:10.09";
        $athlete = 13;
        $stmt->execute();
        $pos = 6;
        $time = "00:00:10.13";
        $athlete = 14;
        $stmt->execute();
        $pos = 7;
        $time = "00:00:10.17";
        $athlete = 15;
        $stmt->execute();
        $pos = 8;
        $time = "00:00:10.20";
        $athlete = 16;
        $stmt->execute();

        $pos = 1;
        $time = "00:00:10.75";
        $event = 3;
        $athlete = 17;
        $stmt->execute();
        $pos = 2;
        $time = "00:00:10.78";
        $athlete = 18;
        $stmt->execute();
        $pos = 3;
        $time = "00:00:10.81";
        $athlete = 19;
        $stmt->execute();
        $pos = 4;
        $time = "00:00:10.85";
        $athlete = 20;
        $stmt->execute();
        $pos = 5;
        $time = "00:00:10.89";
        $athlete = 21;
        $stmt->execute();
        $pos = 6;
        $time = "00:00:10.94";
        $athlete = 22;
        $stmt->execute();
        $pos = 7;
        $time = "00:00:11.00";
        $athlete = 23;
        $stmt->execute();
        $pos = 8;
        $time = "00:00:11.01";
        $athlete = 24;
        $stmt->execute();

        $pos = 1;
        $event = 4;
        $time = "00:00:09.63";
        $athlete = 25;
        $stmt->execute();
        $pos = 2;
        $time = "00:00:09.75";
        $athlete = 26;
        $stmt->execute();
        $pos = 3;
        $time = "00:00:09.79";
        $athlete = 27;
        $stmt->execute();
        $pos = 4;
        $time = "00:00:09.88";
        $athlete = 28;
        $stmt->execute();
        $pos = 5;
        $time = "00:00:09.94";
        $athlete = 29;
        $stmt->execute();
        $pos = 6;
        $time = "00:00:09.89";
        $athlete = 30;
        $stmt->execute();
        $pos = 7;
        $time = "00:00:11.99";
        $athlete = 31;
        $stmt->execute();
        $pos = 8;
        $time = "00:00:12.00";
        $athlete = 32;
        $stmt->execute();

        $pos = 1;
        $event = 5;
        $time = "00:00:10.71";
        $athlete = 33;
        $stmt->execute();
        $pos = 2;
        $time = "00:00:10.83";
        $athlete = 34;
        $stmt->execute();
        $pos = 3;
        $time = "00:00:10.86";
        $athlete = 17;
        $stmt->execute();
        $pos = 4;
        $time = "00:00:10.86";
        $athlete = 35;
        $stmt->execute();
        $pos = 5;
        $time = "00:00:10.90";
        $athlete = 36;
        $stmt->execute();
        $pos = 6;
        $time = "00:00:10.92";
        $athlete = 37;
        $stmt->execute();
        $pos = 7;
        $time = "00:00:10.94";
        $athlete = 38;
        $stmt->execute();
        $pos = 8;
        $time = "00:00:11.80";
        $athlete = 39;
        $stmt->execute();

        $pos = 1;
        $event = 6;
        $time = "00:00:09.81";
        $athlete = 25;
        $stmt->execute();
        $pos = 2;
        $time = "00:00:09.89";
        $athlete = 27;
        $stmt->execute();
        $pos = 3;
        $time = "00:00:09.91";
        $athlete = 40;
        $stmt->execute();
        $pos = 4;
        $time = "00:00:09.93";
        $athlete = 26;
        $stmt->execute();
        $pos = 5;
        $time = "00:00:09.94";
        $athlete = 41;
        $stmt->execute();
        $pos = 6;
        $time = "00:00:09.96";
        $athlete = 42;
        $stmt->execute();
        $pos = 7;
        $time = "00:00:10.04";
        $athlete = 43;
        $stmt->execute();
        $pos = 8;
        $time = "00:00:10.06";
        $athlete = 44;
        $stmt->execute();

        $pos = 1;
        $event = 7;
        $time = "00:00:10.61";
        $athlete = 33;
        $stmt->execute();
        $pos = 2;
        $time = "00:00:10.74";
        $athlete = 17;
        $stmt->execute();
        $pos = 3;
        $time = "00:00:10.76";
        $athlete = 45;
        $stmt->execute();
        $pos = 4;
        $time = "00:00:10.91";
        $athlete = 35;
        $stmt->execute();
        $pos = 5;
        $time = "00:00:10.97";
        $athlete = 46;
        $stmt->execute();
        $pos = 6;
        $time = "00:00:10.99";
        $athlete = 47;
        $stmt->execute();
        $pos = 7;
        $time = "00:00:11.02";
        $athlete = 48;
        $stmt->execute();
        $pos = 8;
        $time = "00:00:11.12";
        $athlete = 49;
        $stmt->execute();

        $pos = 1;
        $event = 8;
        $time = "00:00:09.80";
        $athlete = 50;
        $stmt->execute();
        $pos = 2;
        $time = "00:00:09.84";
        $athlete = 51;
        $stmt->execute();
        $pos = 3;
        $time = "00:00:09.89";
        $athlete = 40;
        $stmt->execute();
        $pos = 4;
        $time = "00:00:09.93";
        $athlete = 41;
        $stmt->execute();
        $pos = 5;
        $time = "00:00:09.95";
        $athlete = 52;
        $stmt->execute();
        $pos = 6;
        $time = "00:00:09.98";
        $athlete = 53;
        $stmt->execute();
        $pos = 7;
        $time = "00:00:10.02";
        $athlete = 54;
        $stmt->execute();
        $pos = 8;
        $time = "00:00:10.11";
        $athlete = 55;
        $stmt->execute();
    }

    private function populateUsers()
    {
        $stmt = $this->connec->prepare("INSERT INTO `users` (name, surname, email, password, athlete, time_created) VALUES (?, ?, ?, ?, ?, ?)");
        $stmt->bind_param("ssssii", $name, $surname, $email, $pass, $ath, $time);
        $name = "Default";
        $surname = "User";
        $email = "default@u.c";
        $pass = "d9d8c68a295f34ad3ef590a4b683f3";
        $ath = 24;
        $time = 1652881570;
        $stmt->execute();

        $name = "Janco";
        $surname = "Spies";
        $email = "j@gmail.com";
        $pass = "2b5c421dfea2e751329c61879de5cf";
        $ath = null;
        $time = 1652955019;
        $stmt->execute();
    }
};

function resetSampleData()
{
    $c = addSampleData::instance();
    $c->loadSampleData();
}
// echo '<br><br><br>';
// echo '<div class = "centered_container" >';
resetSampleData();
// echo '</div>';
